--- 
rubyforge_project: io-reactor
project_requirements: {}

project_description: |-
  A pure-Ruby implementation of an asynchronous multiplexed IO
  Reactor which is based on the Reactor design pattern found in _Pattern-Oriented
  Software Architecture, Volume 2: Patterns for Concurrent and Networked
  Objects_. It allows a single thread to demultiplex and dispatch events from one
  or more IO objects to the appropriate handler.
rubyforge_group: deveiate
author_name: Michael Granger
project_homepage: http://deveiate.org/projects/IO-Reactor/
project_dependencies: {}

project_summary: Multiplexed IO Reactor class
project_name: IO-Reactor
version_file: io/reactor.rb
additional_pkgfiles: 
- examples/*.rb
author_email: ged@FaerieMUD.org
